version: "3.8"
services:
  socket:
    image: node:12
    container_name: socket
    restart: always
    ports:
      - 8888
    volumes:
      - ./socket:/app
    working_dir: /app
    command: node server.js
    networks:
      - app-networks
  nginx:
    image: nginx:latest
    container_name: main-app
    restart: always
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/nginx.conf
      - ./client:/usr/share/nginx/html
    ports:
      - 3001:80
    depends_on:
      - socket
    networks:
      - app-networks
    expose:
      - 3001
networks:
  app-networks: